from setuptools import setup, find_packages

setup(
    name="agentic_systems",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "requests",
        "pydantic",
        "python-dotenv",
        "chromadb",
        "sentence-transformers",
        "ollama",
        "langchain",
        "langchain-community",
        "openai",
        "faiss-cpu",
        "numpy",
        "pandas",
        "fastapi",
        "uvicorn",
        "jinja2",
    ],
    author="Fouad Bousetouane",
    author_email="example@example.com",
    description="Agentic Systems for Vertical AI Agents",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/fouadcorp/agentic-systems",
    project_urls={
        "Bug Tracker": "https://github.com/fouadcorp/agentic-systems/issues",
        "Documentation": "https://github.com/fouadcorp/agentic-systems",
        "Source Code": "https://github.com/fouadcorp/agentic-systems",
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.8",
) 