name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]  # Limiting to Python 3.9 only for now

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install CI dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        # Install from the CI-specific requirements file
        if [ -f ci-requirements.txt ]; then pip install -r ci-requirements.txt; fi
        # Install the package in development mode without dependencies
        pip install -e . --no-deps
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run CI tests
      run: |
        # Run the simple tests that don't require external dependencies
        pytest simple_tests 